<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Safe Disposal of Unexploded WWII Bombs</title>
  <meta name="description" content="Abstract">

  <link rel="stylesheet" href="/blog/css/main.css">
  <link rel="canonical" href="https://mhoehle.github.io/blog/2018/05/25/uxb.html">
  <link rel="alternate" type="application/rss+xml" title="Theory meets practice..." href="https://mhoehle.github.io/blog/feed.xml">
</head>

<!-- https://docs.mathjax.org/en/v2.7-latest/start.html -->
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML">
</script>




  <body>

    <header class="site-header">

  <div class="wrapper">

    <a class="site-title" href="/blog/">Theory meets practice...</a>

    <nav class="site-nav">
      <a href="#" class="menu-icon">
        <svg viewBox="0 0 18 15">
          <path fill="#424242" d="M18,1.484c0,0.82-0.665,1.484-1.484,1.484H1.484C0.665,2.969,0,2.304,0,1.484l0,0C0,0.665,0.665,0,1.484,0 h15.031C17.335,0,18,0.665,18,1.484L18,1.484z"/>
          <path fill="#424242" d="M18,7.516C18,8.335,17.335,9,16.516,9H1.484C0.665,9,0,8.335,0,7.516l0,0c0-0.82,0.665-1.484,1.484-1.484 h15.031C17.335,6.031,18,6.696,18,7.516L18,7.516z"/>
          <path fill="#424242" d="M18,13.516C18,14.335,17.335,15,16.516,15H1.484C0.665,15,0,14.335,0,13.516l0,0 c0-0.82,0.665-1.484,1.484-1.484h15.031C17.335,12.031,18,12.696,18,13.516L18,13.516z"/>
        </svg>
      </a>

      <div class="trigger">
        
          
          <a class="page-link" href="/blog/about/">About</a>
          
        
          
        
          
        
          
        
      </div>
    </nav>

  </div>

</header>


    <div class="page-content">
      <div class="wrapper">
        <article class="post" itemscope itemtype="http://schema.org/BlogPosting">

  <header class="post-header">
    <h1 class="post-title" itemprop="name headline">Safe Disposal of Unexploded WWII Bombs</h1>
    <p class="post-meta"><time datetime="2018-05-25T00:00:00+02:00" itemprop="datePublished">May 25, 2018</time></p>
  </header>

  <div class="post-content" itemprop="articleBody">
    <h2 id="abstract">Abstract</h2>
<p>Unexploded WWII bombs are ticking threats despite being dropped more
than 70 years ago. In this post we explain how statistical methods are
used to plan the search and disposal of unexploded WWII bombs. In
particular we consider and exemplify the non-parametric nearest
neighbour distance (NND) method implemented in the R package
<code>highriskzone</code>. The method analyses the spatial pattern of
exploded bombs to determine so called risk-zones, that is regions with a
high likelihood of containing unexploded bombs. The coverage of such
risk-zones is investigated through both non-parametric and parametric
point process simulation.</p>
<center>
<img
src="https://ncap.org.uk/sites/default/files/frames/download/000/000/022/NCAP-000-000-022-423.jpg" />
</center>
<p><FONT
COLOR="bbbbbb"><a
href="http://ncap.org.uk/NCAP-000-000-022-423">NCAP</a> aerial photo
from 1944 showing the bombing of the V2 rocket facility at Peenemünde,
Germany. Image is available under a custom NCAP license - higher
resolution images are available from NCAP. </FONT></p>
<p><br>
<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"/></a>
This work is licensed under a <a rel="license"
href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons
Attribution-ShareAlike 4.0 International License</a>. The
markdown+Rknitr source code of this blog is available under a <a
href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public
License (GPL v3)</a> license from github.</p>
<p><span class="math display">\[
\newcommand{\bm}[1]{\boldsymbol{\mathbf{#1}}}
\]</span></p>
<h2 id="introduction">Introduction</h2>
<p>During WWII Germany was pounded with about <a
href="https://www.smithsonianmag.com/history/seventy-years-world-war-two-thousands-tons-unexploded-bombs-germany-180957680/">1.5
mio tons of bombs</a> of which about 10-15% did not explode. More than
70 years after the end of WWII these unexploded bombs (UXBs) still pose
a threat and are the frequent cause of large scale evacuations to secure
their <a
href="https://ncap.org.uk/case-studies/explosive-ordnance-disposal">safe
disposal</a> when found. Luckily, lethal incidents are rare thanks to a
huge effort to <a
href="https://www.youtube.com/watch?v=wrIDT26BAt0">localise and safely
dismantle</a> UXBs. As part of this effort, aerial photos taken by the
allies after the attacks provide valuable information about the possible
locations of UXBs. Some UXBs are directly visible in the photos - see
for example the green circles in this <a
href="https://ncap.org.uk/sites/default/files/NCAP_JARIC_106G_4923_4226_UXO_600.jpg">NCAP
image</a> or p. 6 in the following <a
href="https://www.luftbilddatenbank.de/download/luftbilddatenbank.pdf">information
flyer</a> by one of the companies offering such aerial identification
services (featured in this <a
href="http://www.spiegel.de/international/business/firm-uses-historic-aerial-photos-to-find-unexploded-wwii-bombs-a-825836.html">news
article</a>). In other cases the photos only provide information about
the location of the exploded bombs. This information can be used to
identify areas where there is a high likelihood of UXBs. Such areas
would then be carefully scrutinized using on-the-ground search methods,
for example, electromagnetic and magnetic detectors.</p>
<p>The aim of <span class="citation"
data-cites="mahling_etal2013">Mahling, Höhle, and Küchenhoff
(2013)</span> was to develop statistical methods for the identification
of such risk-zones in co-operation with <em>Oberfinanzdirektion
Niedersachsen</em>, which supports the removal of unexploded ordnance in
federal properties in Germany. In what follows we will discuss
<em>one</em> of the methods used in the paper, the so called
<strong>nearest neighbourhood distance method</strong> and illustrate
its implementation in the R package <code>highriskzone</code> originally
created by <a href="http://heidiseibold.github.io">Heidi Seibold</a> and
now maintained by <a
href="http://www.stablab.stat.uni-muenchen.de/personen/doktoranden/guenther/index.html">Felix
Günther</a>.</p>
<h3 id="mathematical-setup">Mathematical Setup</h3>
<p>Casting matters into mathematical notation: Let <span
class="math inline">\(X\)</span> be a point process denoting the spatial
locations of all bombs dropped in the particular window of interest
<span class="math inline">\(W \subseteq \mathbb{R}^2\)</span>.
Furthermore, let <span class="math inline">\(Y\)</span> denote the
observed point process of exploded bomb and <span
class="math inline">\(Z=X\backslash Y\)</span> the point process of
unexploded bombs. Note that only the process <span
class="math inline">\(Y\)</span> is observed; <span
class="math inline">\(Z\)</span> is not observed and the target of our
inference. We assume that the probability <span
class="math inline">\(q\)</span> of a dropped bomb not exploding is
homogeneous in <span class="math inline">\(W\)</span>. Thus if <span
class="math inline">\(X\)</span> is a inhomogeneous Poisson point
process with intensity function <span
class="math inline">\(\lambda_X(\bm{s})\)</span>, <span
class="math inline">\(\bm{s}\in W\)</span>, then</p>
<p><span class="math display">\[
\lambda_Y(\bm{s}) = (1-q) \lambda_X(\bm{s})
\quad \text{and}\quad
\lambda_Z(\bm{s}) = q \lambda_X(\bm{s})
\]</span></p>
<p>are the intensity functions of <span class="math inline">\(Y\)</span>
and <span class="math inline">\(Z\)</span>, respectively.</p>
<p>The figure below shows <span class="math inline">\(Y\)</span> for an
actual observed WWII bomb point consisting of n=443 bombs available from
the R package <code>highriskzone</code> <span class="citation"
data-cites="highriskzone">(Seibold et al. 2017)</span>. The observation
window contains a particular area of interest for which a risk
assessment needs to be done - often these contain a known WWII military
target, e.g., an airport, an arms factory or a military casern. In order
to not disclose the exact location of the considered area, coordinates
are given relative to an arbitrary origo. In reality one would closely
link such digitized aerial images to other terrain features using a GIS
system.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(highriskzone)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatstat)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(craterA)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(craterA)</span></code></pre></div>
<pre><code>## Planar point pattern:  443 points
## Average intensity 0.0001082477 points per square unit
## 
## Coordinates are given to 4 decimal places
## 
## Window: polygonal boundary
## single connected closed polygon with 208 vertices
## enclosing rectangle: [0, 2334.3758] x [0, 2456.4061] units
## Window area = 4092470 square units
## Fraction of frame area: 0.714</code></pre>
<p><img src="/blog/figure/source/2018-05-25-uxb/unnamed-chunk-5-1.png" title="Observed bomb point pattern ($Y$) within the observation window $W$." alt="Observed bomb point pattern ($Y$) within the observation window $W$." style="display: block; margin: auto;" />
The point pattern <code>craterA</code> corresponding to an instance of
the process <span class="math inline">\(Y\)</span> is provided in R as
an object of class ppp from the R package <code>spatstat</code> <span
class="citation" data-cites="baddeley_etal2015">(Baddeley, Rubak, and
Turner 2015)</span>. Instead of inferring the locations in <span
class="math inline">\(Z\)</span> directly, we shall be interested in
determining a region within <span class="math inline">\(W\)</span>, a so
called <strong>high risk zone</strong>, which with a high likelihood
contains the points of <span class="math inline">\(Z\)</span>. We shall
consider two methods for this job: a non-parametric method based on
nearest neighbour distances in <span class="math inline">\(Y\)</span>
and an intensity function based inhomogeneous Poisson process approach
incorporating <span class="math inline">\(q\)</span>.</p>
<h3 id="high-risk-zones">High Risk Zones</h3>
<p>A heuristic way to determine a high-risk zone is the following:
Determine the distribution function <span
class="math inline">\(D\)</span> of the nearest neighbour distance (NND)
distribution based on the 443 points in the point pattern. Use the
distribution to determine a desired quantile, say <span
class="math inline">\(0 \leq p \leq 1\)</span> of the NND distribution.
Denoting the <span class="math inline">\(p\)</span> sample quantile of
the NND distribution by <span class="math inline">\(Q(p)\)</span>, a
<span class="math inline">\(p\)</span>-quantile NND based high-risk zone
is then obtained as the union of putting a disc of radius <span
class="math inline">\(x_q\)</span> around each observed exploded bomb in
<span class="math inline">\(Y\)</span> - in mathematical terms:</p>
<p><span class="math display">\[
R_p = \left(\bigcup_{\bm{y} \in Y} B(\bm{y}, Q(p))\right) \bigcap W =
\left\{\bm{s} \in W : \min_{\bm{y}\in Y} || \bm{s} − \bm{y} || \leq
Q_Y(p) \right\},
\]</span></p>
<p>where <span class="math inline">\(B(\bm{s}, r)\)</span> denotes a
disc of radius <span class="math inline">\(r\)</span> around the point
<span class="math inline">\(\bm{s}\)</span> and <span
class="math inline">\(||\bm{s} - \bm{y}||\)</span> is the distance
between the two points <span class="math inline">\(\bm{s}\)</span> and
<span class="math inline">\(\bm{y}\)</span>. The intersection with <span
class="math inline">\(W\)</span> is done in order to guarantee that the
risk zone lies entirely within <span class="math inline">\(W\)</span>.
As an example, we would determine the 99%-quantile NND zone for
<code>craterA</code> using <code>spatstat</code> functionality as
follows:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>(Qp <span class="ot">&lt;-</span> <span class="fu">quantile</span>(<span class="fu">nndist</span>(craterA), <span class="at">p =</span> <span class="fl">0.99</span>, <span class="at">type =</span> <span class="dv">8</span>))</span></code></pre></div>
<pre><code>##      99% 
## 142.1391</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dmap <span class="ot">&lt;-</span> <span class="fu">distmap</span>(craterA)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>zone_dist <span class="ot">&lt;-</span> <span class="fu">eval.im</span>( dmap <span class="sc">&lt;</span> Qp )</span></code></pre></div>
<p>The above can also be done directly using
<code>highriskzone::det_hrz</code> function:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>zone_dist <span class="ot">&lt;-</span> <span class="fu">det_hrz</span>(craterA, <span class="at">type=</span><span class="st">&quot;dist&quot;</span>, <span class="at">criterion =</span> <span class="st">&quot;indirect&quot;</span>, <span class="at">cutoff=</span><span class="fl">0.99</span>)</span></code></pre></div>
<p>Either way, the resulting risk-zone is as follows:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(zone_dist)</span></code></pre></div>
<pre><code>## high-risk zone of type dist  
## criterion: indirect  
## cutoff: 0.99  
##  
## threshold: 142.1391  
## area of the high-risk zone: 2580654</code></pre>
<p><img src="/blog/figure/source/2018-05-25-uxb/unnamed-chunk-9-1.png" style="display: block; margin: auto;" />
<span class="citation" data-cites="mahling_etal2013">Mahling, Höhle, and
Küchenhoff (2013)</span> show that risk zones constructed by the NND
method work surprisingly well despite lacking a clear theoretical
justification. One theoretical issue is, for example, that the NND
distribution function determined by the above method is for the <span
class="math inline">\((1-q)\)</span> thinned process <span
class="math inline">\(Y\)</span>, even though the actual interest is in
the process <span class="math inline">\(X=Y\cup Z\)</span>. Because of
the thinning one would typically have that <span
class="math inline">\(D_Y(r) \leq D_X(r)\)</span> and thus <span
class="math inline">\(Q_Y(p) &gt; Q_X(p)\)</span>. Using <span
class="math inline">\(Q_Y(p)\)</span> to make statements about <span
class="math inline">\(X\)</span> (and thus <span
class="math inline">\(Z\)</span>) is therefore slightly wrong. However,
this error cancels, because we then use the points in <span
class="math inline">\(Y\)</span> to add a buffer of radius <span
class="math inline">\(Q_Y(p)\)</span>. Had we instead used the smaller,
but true, <span class="math inline">\(Q_X(p)\)</span> the risk zone
would have gotten a too small, because <span
class="math inline">\(X\)</span> would also have contained more points
to form discs around than <span class="math inline">\(Y\)</span>. The
method thus implicitly takes <span class="math inline">\(q\)</span>
non-parametrically into account, because its NND is determined based on
<span class="math inline">\(Y\)</span> and subsequently discs of radius
<span class="math inline">\(Q_Y(p)\)</span> are formed around the points
of <span class="math inline">\(Y\)</span>.</p>
<div class="framedbox">
<p>Technical details you might want to skip: The above feature is most
easily illustrated if <span class="math inline">\(X\)</span> is a
homogeneous Poisson process with intensity <span
class="math inline">\(\lambda_X\)</span>. In this case we have that the
NND distribution function is <span class="citation"
data-cites="illian_etal2008">(p.68, Illian et al. 2008)</span></p>
<p><span class="math display">\[
D_X(r) = 1 - \exp(-\lambda_X \pi r^2), \quad r&gt;0.
\]</span></p>
<p>Also note that <span class="math inline">\(D_Y(r) = 1 -
\exp(-(1-q)\lambda_X \pi r^2)\)</span> and therefore <span
class="math inline">\(D_Y(r) &gt; D_X(r)\)</span>. Now solving for the
<span class="math inline">\(p\)</span>-quantile of the NND in this
homogeneous Poisson case means solving</p>
<p><span class="math display">\[
Q_Y(p) = \min_{r\geq 0} \{ D_Y(r) \geq p \} \Leftrightarrow Q_Y(p) =
\sqrt{ \frac{\log(1-p)}{\lambda_Y \pi}}.
\]</span></p>
<p>From this it becomes clear than in the homogeneous Poisson case <span
class="math inline">\(Q_
Y(p)\)</span> is a factor <span
class="math inline">\(\sqrt{1/(1-q)}\)</span> larger than <span
class="math inline">\(Q_X(p)\)</span>, which is the actual target of
interest.</p>
</div>
<p>
<h3 id="assessing-the-coverage-of-a-risk-zone">Assessing the coverage of
a risk-zone</h3>
<p>Two criterion appear immediate in order to assess the coverage of a
risk-zone <span class="math inline">\(R\)</span>:</p>
<ol type="1">
<li><p>The probability <span
class="math inline">\(p_{\text{out}}\)</span> that there will be at
least one bomb outside the risk zone, i.e. <span
class="math inline">\(P( N( Z \backslash R) &gt; 0)\)</span>, where
<span class="math inline">\(N(A)\)</span> denotes the number of events
in the set <span class="math inline">\(A \subseteq W\)</span>. Note:
this probability is depending heavily on the amount of points in <span
class="math inline">\(Z\)</span>, the more points there are, the higher
is <span class="math inline">\(p_{\text{out}}\)</span>. However, it
reflects the idea “one miss is all it takes to get in trouble”.</p></li>
<li><p>The proportion of events in <span
class="math inline">\(Z\)</span> not located in <span
class="math inline">\(R\)</span>, i.e. <span class="math inline">\(N( Z
\backslash R) / N(Z)\)</span>, we shall denote this criterion by <span
class="math inline">\(p_{\text{miss}}\)</span>. Note: This probability
is taking possible different sizes of <span
class="math inline">\(Z\)</span> into account, but also takes a more
relative approach towards how many bombs are not covered by the
zone.</p></li>
</ol>
<p>Under the assumption of independence between whether <span
class="math inline">\(Z\)</span>-events are within or outside the
risk-zone one can convert back and forth between <span
class="math inline">\(p_{\text{miss}}\)</span> and <span
class="math inline">\(p_{\text{out}}\)</span> by</p>
<p><span class="math display">\[
p_{\text{out}} = P( N( Z \backslash R) &gt; 0) = 1- P(N(Z
\backslash R) = 0) \approx  1 - (1-p_{\text{miss}})^{N(Z)},
\]</span></p>
<p>where one in a simulation setup would know <span
class="math inline">\(Z\)</span> and thus also <span
class="math inline">\(N(Z)\)</span>. Note that for a <span
class="math inline">\(p\)</span>-quantile NND risk-zone we expect <span
class="math inline">\(1-p_{\text{miss}}\)</span> to be approximately
equal to <span class="math inline">\(p\)</span>. We can investigate the
behaviour of risk-zones according to the two above criterion through the
use of simulation. Either by simply <span
class="math inline">\(q\)</span>-thinning of the existing point pattern
<span class="math inline">\(Y\)</span> and then use this thinned pattern
to determine a risk-zone, which is then evaluated. An alternative
approach is to estimate the intensity surface from <span
class="math inline">\(Y\)</span>, upscale it to get the intensity of
<span class="math inline">\(X\)</span>, simulate <span
class="math inline">\(X\)</span> as an inhomogeneous Poisson point
process with this intensity surface, thin this pattern to get a
simulated instance of <span class="math inline">\(Y\)</span>, construct
the risk-zone based on this pattern and then evaluate the coverage of
the zone <span class="citation" data-cites="mahling_etal2013">(Mahling,
Höhle, and Küchenhoff 2013)</span>. Note that this type of simulation is
based on more assumptions compared to the non-parametric thinning
simulation approach.</p>
<p>We generate 1,000 realizations of <span
class="math inline">\(Y\)</span> and <span
class="math inline">\(Z\)</span> through <span
class="math inline">\(q\)</span>-thinning of the original
<code>craterA</code> pattern while computing the coverage measures for
the NND method as follows:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(doParallel))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">registerDoParallel</span>(<span class="at">cores=</span><span class="dv">4</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>simulate_method <span class="ot">&lt;-</span> <span class="st">&quot;thinning&quot;</span> <span class="co">#&quot;intensity&quot; # &quot;cond_intensity&quot;</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>sim <span class="ot">&lt;-</span> <span class="fu">foreach</span>(<span class="at">i=</span><span class="fu">seq_len</span>(<span class="fu">getDoParWorkers</span>()), <span class="at">.combine=</span>rbind) <span class="sc">%dopar%</span> {</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tryCatch</span>(</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">eval_method</span>(craterA, <span class="at">type=</span><span class="fu">c</span>(<span class="st">&quot;dist&quot;</span>), <span class="at">criterion=</span><span class="fu">c</span>(<span class="st">&quot;indirect&quot;</span>),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">cutoff=</span><span class="fl">0.99</span>, <span class="at">numit =</span> <span class="dv">250</span>, <span class="at">simulate=</span>simulate_method,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">pbar=</span><span class="cn">FALSE</span>),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">error=</span> <span class="cf">function</span>(e) <span class="fu">return</span>(<span class="cn">NULL</span>))</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   p_out  p_miss `1-p_miss` p_out_derived    nZ
##   &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;
## 1 0.097 0.00236      0.998        0.0996  44.4</code></pre>
<p>The numbers state the average <code>p_out</code> and
<code>p_miss</code>in the 1000 simulations. Furthermore, <code>nZ</code>
denotes the average number of events in <span
class="math inline">\(Z\)</span>. We see that the NND method performs
even a little better than intended, because <span
class="math inline">\(1-p_{\text{miss}}\)</span> is even higher than the
intended <span class="math inline">\(p\)</span>=99%. The probability
that the risk-zone misses at least one bomb lies as low as 0.097. This
is quite close to the above described approximate conversion from <span
class="math inline">\(p_{\text{miss}}\)</span> (0.100 vs. 0.097).
Changing the simulation method for <span
class="math inline">\(X\)</span> to that of an inhomogeneous Poisson
process with intensity <span class="math inline">\(1/(1-q) \cdot
\hat{\lambda}_Y(\bm{s})\)</span> yields similar results:</p>
<pre><code>## # A tibble: 1 x 5
##   p_out  p_miss `1-p_miss` p_out_derived    nZ
##   &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;
## 1 0.352 0.00897      0.991         0.361  49.6</code></pre>
<p>We note that the probability of missing at least one bomb is much
higher under this parametric simulation method. Only a small fraction of
this is explained by <span class="math inline">\(Z\)</span> now
consisting of more points. A likely explanation is that the parametric
model is only semi-adequate to describe how the point patterns form.
Therefore, the new <span class="math inline">\(X\)</span> might have a
somewhat different neighbourhood distribution than anticipated.</p>
<p>To compare more specifically with the intensity function based
risk-zone method of <span class="citation"
data-cites="mahling_etal2013">Mahling, Höhle, and Küchenhoff
(2013)</span> we use a specification, where the risk-zone derived by the
NND method or the intensity method have the same area (250 hectare).</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>sim_area <span class="ot">&lt;-</span> <span class="fu">foreach</span>(<span class="at">i=</span><span class="fu">seq_len</span>(<span class="fu">getDoParWorkers</span>()), <span class="at">.combine=</span>rbind) <span class="sc">%dopar%</span> {</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tryCatch</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">eval_method</span>(craterA, <span class="at">type=</span><span class="fu">c</span>(<span class="st">&quot;dist&quot;</span>,<span class="st">&quot;intens&quot;</span>), <span class="at">criterion=</span><span class="fu">rep</span>(<span class="st">&quot;area&quot;</span>,<span class="dv">2</span>),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">cutoff=</span><span class="fu">rep</span>(<span class="dv">2500000</span>,<span class="dv">2</span>), <span class="at">numit =</span> <span class="dv">100</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">simulate=</span>simulate_method, <span class="at">pbar=</span><span class="cn">FALSE</span>),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">error=</span> <span class="cf">function</span>(e) <span class="fu">return</span>(<span class="cn">NULL</span>))</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## # A tibble: 2 x 6
##   Type   p_out  p_miss `1-p_miss` p_out_derived area_zone
##   &lt;fct&gt;  &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt;
## 1 dist   0.123 0.00278      0.997         0.117  2500009.
## 2 intens 0.55  0.0172       0.983         0.539  2499994.</code></pre>
<p>For the particular example we see an advantage of using the NND
method, because both <code>p_out</code> <code>p_miss</code> are much
lower for the intensity based method. Again, this might be due to the
intensity method being based on assumptions, which for the particular
example do not appear to be so adequate. Results in <span
class="citation" data-cites="mahling2013">Mahling (2013)</span> were,
however, much better for this example (c.f. Tab 2), which could be an
indication that there is a problem in the <code>highriskzone</code>
package implementation of this method?</p>
<h2 id="discussion">Discussion</h2>
<p>Being a statistician is fascinating, because the job is the entry
ticket to so many diverse research fields. The proposed methods and
evaluations helped the <em>Oberfinanzdirektion</em> obtain a
quantitative framework to decide which methods to use in their routine
risk-assessment. Further details on the above application can be found
in <span class="citation" data-cites="mahling_etal2013">Mahling, Höhle,
and Küchenhoff (2013)</span> as well as in <a
href="https://edoc.ub.uni-muenchen.de/15886/">Monia’s
Ph.D. dissertation</a> <span class="citation"
data-cites="mahling2013">(Mahling 2013)</span>. Note also that the
techniques are not limited to UXB detection:
Infer-unknown-points-from-a-thinned-process problems occur both in 1D
and 2D point processes in a range of other fields, e.g., under-reporting
of infectious disease locations or in the calculation of animal
abundance in ecology.</p>
<p>As a personal anecdote: When finishing the work on <span
class="citation" data-cites="mahling_etal2013">Mahling, Höhle, and
Küchenhoff (2013)</span> I was in transition from university to working
at a public health institute. The deal was to finish the UXB work partly
in spare-time and partly in the new work time. To honour this I added my
new work place as second affiliation before submitting, but as part of
the institution’s internal clearing procedure of the publication, I was
asked to remove this affiliation again by the higher management, because
the work ‘had nothing to do with public health’. While its questionable
whether exploding bombs really do not have a public health impact, a few
months later, I ended up using very similar statistical techniques to
model occurred-but-not-yet-reported cases during a critical infectious
disease outbreak <span class="citation"
data-cites="hoehle_anderheiden2014">(Höhle and an der Heiden
2014)</span>.</p>
<center>
<a title="By No 4 RAFFPU, Royal Air Force official photographer [Public domain], via Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File:Grand_Slam_bomb_exploding_near_Arnsberg_viaduct_1945.jpg"><img width="512" alt="Grand Slam bomb exploding near Arnsberg viaduct 1945" src="https://upload.wikimedia.org/wikipedia/commons/2/2c/Grand_Slam_bomb_exploding_near_Arnsberg_viaduct_1945.jpg"></a>
</center>
<p>
<h2 class="unnumbered" id="literature">Literature</h2>
<div id="refs" class="references csl-bib-body hanging-indent"
data-entry-spacing="0" role="list">
<div id="ref-baddeley_etal2015" class="csl-entry" role="listitem">
Baddeley, A., E. Rubak, and R. Turner. 2015. <em>Spatial Point Patterns:
Methodology and Applications with <span>R</span></em>. London: Chapman;
Hall/CRC. <a
href="http://www.crcpress.com/books/details/9781482210200/">http://www.crcpress.com/books/details/9781482210200/</a>.
</div>
<div id="ref-hoehle_anderheiden2014" class="csl-entry" role="listitem">
Höhle, M., and M. an der Heiden. 2014. <span>“Bayesian Nowcasting During
the <span>STEC O104:H4</span> Outbreak in <span>Germany</span>,
2011.”</span> <em>Biometrics</em> 70 (4): 993–1002. <a
href="https://doi.org/10.1111/biom.12194">https://doi.org/10.1111/biom.12194</a>.
</div>
<div id="ref-illian_etal2008" class="csl-entry" role="listitem">
Illian, J., A. Penttinen, H. Stoyan, and D. Stoyan. 2008. <em>Stistical
Analysis and Modelling of Spatial Point Patterns</em>. Wiley.
</div>
<div id="ref-mahling2013" class="csl-entry" role="listitem">
Mahling, M. 2013. <span>“Determining High-Risk Zones by Using Spatial
Point Process Methodology.”</span> PhD thesis, Department of Statistics,
University of Munich. <a
href="https://edoc.ub.uni-muenchen.de/15886/1/Mahling_Monia.pdf">https://edoc.ub.uni-muenchen.de/15886/1/Mahling_Monia.pdf</a>.
</div>
<div id="ref-mahling_etal2013" class="csl-entry" role="listitem">
Mahling, M., M. Höhle, and H. Küchenhoff. 2013. <span>“<span
class="nocase">Determining high-risk zones for unexploded World War II
bombs by using point process methodology</span>.”</span> <em>Journal of
the Royal Statistical Society, Series C</em> 62 (2): 181–99. <a
href="https://doi.org/10.1111/j.1467-9876.2012.01055.x">https://doi.org/10.1111/j.1467-9876.2012.01055.x</a>.
</div>
<div id="ref-highriskzone" class="csl-entry" role="listitem">
Seibold, H., M. Mahling, S. Linne, and F. Günther. 2017.
<em>Highriskzone: Determining and Evaluating High-Risk Zones</em>. <a
href="https://cran.r-project.org/web/packages/highriskzone/index.html">https://cran.r-project.org/web/packages/highriskzone/index.html</a>.
</div>
</div>

  </div>

</article>

	

      </div>
    </div>

    <footer class="site-footer">

  <div class="wrapper">

    <h2 class="footer-heading">Theory meets practice...</h2>

    <div class="footer-col-wrapper">
      <div class="footer-col footer-col-1">
        <ul class="contact-list">
          <li>Theory meets practice...</li>
          <li><a href="https://math-inf.uni-greifswald.de/en/michael-hoehle/">Michael Höhle</a></li>
        </ul>
      </div>

      <div class="footer-col footer-col-2">
        <ul class="social-media-list">
          
          <li>
            <a href="https://github.com/mhoehle"><span class="icon icon--github"><svg viewBox="0 0 16 16"><path fill="#828282" d="M7.999,0.431c-4.285,0-7.76,3.474-7.76,7.761 c0,3.428,2.223,6.337,5.307,7.363c0.388,0.071,0.53-0.168,0.53-0.374c0-0.184-0.007-0.672-0.01-1.32 c-2.159,0.469-2.614-1.04-2.614-1.04c-0.353-0.896-0.862-1.135-0.862-1.135c-0.705-0.481,0.053-0.472,0.053-0.472 c0.779,0.055,1.189,0.8,1.189,0.8c0.692,1.186,1.816,0.843,2.258,0.645c0.071-0.502,0.271-0.843,0.493-1.037 C4.86,11.425,3.049,10.76,3.049,7.786c0-0.847,0.302-1.54,0.799-2.082C3.768,5.507,3.501,4.718,3.924,3.65 c0,0,0.652-0.209,2.134,0.796C6.677,4.273,7.34,4.187,8,4.184c0.659,0.003,1.323,0.089,1.943,0.261 c1.482-1.004,2.132-0.796,2.132-0.796c0.423,1.068,0.157,1.857,0.077,2.054c0.497,0.542,0.798,1.235,0.798,2.082 c0,2.981-1.814,3.637-3.543,3.829c0.279,0.24,0.527,0.713,0.527,1.437c0,1.037-0.01,1.874-0.01,2.129 c0,0.208,0.14,0.449,0.534,0.373c3.081-1.028,5.302-3.935,5.302-7.362C15.76,3.906,12.285,0.431,7.999,0.431z"/></svg>
</span><span class="username">mhoehle</span></a>

          </li>
          

          
          <li>
            <a href="https://twitter.com/m_hoehle"><span class="icon icon--twitter"><svg viewBox="0 0 16 16"><path fill="#828282" d="M15.969,3.058c-0.586,0.26-1.217,0.436-1.878,0.515c0.675-0.405,1.194-1.045,1.438-1.809c-0.632,0.375-1.332,0.647-2.076,0.793c-0.596-0.636-1.446-1.033-2.387-1.033c-1.806,0-3.27,1.464-3.27,3.27 c0,0.256,0.029,0.506,0.085,0.745C5.163,5.404,2.753,4.102,1.14,2.124C0.859,2.607,0.698,3.168,0.698,3.767 c0,1.134,0.577,2.135,1.455,2.722C1.616,6.472,1.112,6.325,0.671,6.08c0,0.014,0,0.027,0,0.041c0,1.584,1.127,2.906,2.623,3.206 C3.02,9.402,2.731,9.442,2.433,9.442c-0.211,0-0.416-0.021-0.615-0.059c0.416,1.299,1.624,2.245,3.055,2.271 c-1.119,0.877-2.529,1.4-4.061,1.4c-0.264,0-0.524-0.015-0.78-0.046c1.447,0.928,3.166,1.469,5.013,1.469 c6.015,0,9.304-4.983,9.304-9.304c0-0.142-0.003-0.283-0.009-0.423C14.976,4.29,15.531,3.714,15.969,3.058z"/></svg>
</span><span class="username">m_hoehle</span></a>

          </li>
          
        </ul>
      </div>

      <div class="footer-col footer-col-3">
        <p>A blog about statistics in theory and practice. Not always serious, not always flawless, but definitely a statistically flavoured bean.
</p>
      </div>
    </div>

  </div>

</footer>


  </body>

</html>
